name: Auto Cleanup Old Deployments (v3 Syntax)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup old Cloudflare Pages deployments
        env:
          # 直接使用 Secrets，无需 export
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          echo "Using the environment's default wrangler version..."
          # 验证 wrangler 版本，您会看到这是一个 v3+ 版本
          wrangler --version

          echo "Fetching deployment list for project: $PROJECT_NAME"
          
          # Wrangler v3 的新语法：
          # 1. 'deployment' 是单数
          # 2. 输出是表格格式，不再支持 --json
          # 3. 我们用 awk 来解析表格，提取第一列的部署 ID
          #    NR>2 的意思是跳过表头和分隔线
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | awk 'NR>2 {print $1}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found or failed to fetch list. Exiting."
            exit 0
          fi

          echo "All deployment IDs found:"
          echo "$DEPLOY_IDS"

          # 计算部署数量
          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          # 提取需要删除的旧部署 ID（跳过最新的2个）
          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted:"
          echo "$OLD_IDS"

          # 循环删除旧部署
          for ID in $OLD_IDS; do
            echo "Deleting deployment $ID..."
            # Wrangler v3 的删除语法：
            # 1. 'deployment' 是单数
            # 2. 部署 ID 是一个直接的参数，而不是用 --deployment-id
            # 3. 使用 --force 来避免交互式确认
            wrangler pages deployment delete "$ID" --project-name "$PROJECT_NAME" --force
          done

          echo "✅ Old deployments cleanup completed successfully."
