name: Auto Cleanup Old Deployments

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ← 触发源工作流名称，必须和你仓库的同步任务一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装依赖（jq + 兼容版本 wrangler）
        run: |
          sudo apt-get install -y jq
          npm install -g wrangler@2.20.0  # ✅ 兼容 pages deployments 命令

      - name: 自动清理旧部署（仅保留最新2个）
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ← 替换为你的实际项目名
        run: |
          echo "账户 ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "项目名: $PROJECT_NAME"
          echo "wrangler版本: $(wrangler --version)"

          # 获取部署列表（按时间倒序）
          echo "获取部署列表..."
          DEPLOY_JSON=$(wrangler pages deployments list \
            --project-name="$PROJECT_NAME" \
            --account-id="$CLOUDFLARE_ACCOUNT_ID" \
            --json)

          # 打印原始部署数据
          echo "部署 JSON：$DEPLOY_JSON"

          # 提取部署 ID（保留最新2个，删除其余）
          DEPLOY_IDS=$(echo "$DEPLOY_JSON" | jq -r '.[].id')
          echo "所有部署 ID:"
          echo "$DEPLOY_IDS"

          # 判断是否需要清理
          if [ $(echo "$DEPLOY_IDS" | wc -l) -le 2 ]; then
            echo "部署数量不超过2个，无需清理。"
            exit 0
          fi

          # 提取旧部署 ID（跳过前2个）
          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "即将删除旧部署:"
          echo "$OLD_IDS"

          for ID in $OLD_IDS; do
            echo "正在删除部署 $ID"
            wrangler pages deployments delete \
              --project-name="$PROJECT_NAME" \
              --account-id="$CLOUDFLARE_ACCOUNT_ID" \
              --deployment-id="$ID" \
              --yes
          done

          echo "✅ 旧部署清理完成！"
