name: Auto Cleanup Old Deployments (Final Tool Version with xargs)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest wrangler and cleanup old deployments
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          set -e

          echo "Installing the latest version of wrangler..."
          npm install -g wrangler
          
          echo "Installation complete. Verifying version..."
          wrangler --version

          echo "Fetching deployment list for project: $PROJECT_NAME"
          
          # 解析命令保持不变，它能正确地从表格中提取干净的ID列表
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | tr -d '\r' | grep '^│' | awk '{print $2}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found. Exiting."
            exit 0
          fi
          
          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted using xargs:"
          echo "$OLD_IDS"

          # 终极修复：放弃所有shell循环，使用 xargs 来构建和执行命令，以绕过shell的解析BUG
          # -I {} : 告诉 xargs 将每一行输入的内容，替换掉后面命令中的 {} 占位符
          echo "$OLD_IDS" | xargs -I {} wrangler pages deployment delete {} --project-name "$PROJECT_NAME" --force

          echo "✅ Old deployments cleanup completed successfully."
