- name: 自动删除旧部署（仅保留最新2个）
  env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    PROJECT_NAME: "libretv"
  run: |
    echo "获取部署列表..."
    DEPLOY_JSON=$(wrangler pages deployments list --project-name="$PROJECT_NAME" --account-id="$CLOUDFLARE_ACCOUNT_ID" --json)

    echo "获取到的部署列表：$DEPLOY_JSON"

    DEPLOY_IDS=$(echo "$DEPLOY_JSON" | jq -r '.[].id' | tail -n +3)

    if [ -n "$DEPLOY_IDS" ]; then
      echo "开始删除旧部署：$DEPLOY_IDS"
      for ID in $DEPLOY_IDS; do
        wrangler pages deployments delete --project-name="$PROJECT_NAME" --account-id="$CLOUDFLARE_ACCOUNT_ID" --deployment-id="$ID" --yes
      done
      echo "旧部署清理完成！"
    else
      echo "无需清理，仅保留了最新2个部署"
    fi
