name: Auto Cleanup Old Deployments (Final Solution - Direct API Call)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup old deployments via Cloudflare API
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          set -e

          # 我们仍然需要 wrangler 来“获取”部署列表，因为这个功能是好的
          echo "Installing wrangler to list deployments..."
          npm install -g wrangler
          wrangler --version

          echo "Fetching deployment list..."
          
          # 这部分的解析逻辑是正确的，继续使用
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | tr -d '\r' | grep '^│' | awk '{print $2}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found. Exiting."
            exit 0
          fi
          
          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted via API call:"
          echo "$OLD_IDS"

          # 使用健壮的 `while read` 循环来处理ID
          echo "$OLD_IDS" | while read -r ID; do
            if [ -n "$ID" ]; then
              echo "---"
              echo "Deleting deployment $ID by calling Cloudflare API directly..."
              
              # 终极方案：使用 curl 直接调用 Cloudflare API 来删除部署
              # -X DELETE: 指定 HTTP 请求方法为 DELETE
              # -H "Authorization: Bearer ...": 传递 API Token 进行认证
              # --fail: 如果HTTP响应码不是2xx（成功），则命令失败退出
              API_URL="https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments/$ID"
              
              curl --request DELETE "$API_URL" \
                   --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                   --fail \
                   --silent
              
              echo "Successfully sent DELETE request for deployment $ID."
            fi
          done

          echo "✅ Old deployments cleanup completed successfully."
