name: Auto Cleanup Old Deployments
on:
  workflow_run:
    workflows: ["Upstream Sync"]  # 确保与同步工作流名称一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 jq 和指定版本 wrangler（避免语法问题）
        run: |
          sudo apt-get install -y jq
          npm install -g wrangler@3.57.0  # 使用稳定版本，避免最新版语法变更

      - name: 自动删除旧部署（仅保留最新2个）
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # 替换为你的 Cloudflare Pages 项目名
        run: |
          # 关键修复：使用最新版 wrangler 语法获取部署列表
          DEPLOY_IDS=$(wrangler pages deployments list $PROJECT_NAME --account-id=$CF_ACCOUNT_ID --json | jq -r '.[].id' | tail -n +3)
          
          if [ -n "$DEPLOY_IDS" ]; then
            echo "===== 开始删除旧部署 ====="
            echo "$DEPLOY_IDS"
            for ID in $DEPLOY_IDS; do
              wrangler pages deployments delete $PROJECT_NAME --account-id=$CF_ACCOUNT_ID --deployment-id=$ID --yes
            done
            echo "===== 旧部署清理完成 ====="
          else
            echo "===== 无需清理，仅保留了最新2个部署 ====="
          fi
