name: Auto Cleanup Old Deployments
on:
  workflow_run:
    workflows: ["Sync upstream"]
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 jq 和最新版 wrangler
        run: |
          sudo apt-get install -y jq
          npm install -g wrangler  # 安装最新版 Cloudflare CLI 工具
          
      - name: 强制清理旧部署（仅保留最新2个）
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # 新增：账户ID
        run: |
          # 核心命令：获取所有部署ID（按时间倒序），跳过前2个，删除剩余
          DEPLOY_IDS=$(wrangler pages deployment list libretv --account-id=$CLOUDFLARE_ACCOUNT_ID --format=json | jq -r '.[].id' | tail -n +3)
          
          if [ -n "$DEPLOY_IDS" ]; then
            echo "===== 开始删除以下旧部署 ====="
            echo "$DEPLOY_IDS"
            for ID in $DEPLOY_IDS; do
              echo "删除部署 ID: $ID"
              wrangler pages deployment delete libretv --account-id=$CLOUDFLARE_ACCOUNT_ID --deployment-id=$ID --yes  # --yes 自动确认
            done
            echo "===== 旧部署清理完成 ====="
          else
            echo "===== 无需清理，仅保留了最新2个部署 ====="
          fi
