name: Auto Cleanup Old Deployments (Ultimate Sanitization Version)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest wrangler and cleanup old deployments
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          set -e

          echo "Installing the latest version of wrangler..."
          npm install -g wrangler
          
          echo "Installation complete. Verifying version..."
          wrangler --version

          echo "Fetching deployment list for project: $PROJECT_NAME"
          
          # 解析图形化表格，提取ID
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | tr -d '\r' | grep '^│' | awk '{print $2}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found or failed to fetch list. Exiting."
            exit 0
          fi
          
          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted:"
          echo "$OLD_IDS"

          # 使用健壮的 `while read` 循环
          echo "$OLD_IDS" | while read -r ID; do
            if [ -n "$ID" ]; then
              # 终极修复：强制净化ID，只保留字母、数字和连字符
              CLEAN_ID=$(echo "$ID" | sed 's/[^a-zA-Z0-9-]//g')
              
              # 增加调试输出，对比净化前后的ID
              echo "---"
              echo "Attempting to delete..."
              echo "Original ID from list: [$ID]"
              echo "Sanitized ID for use:  [$CLEAN_ID]"

              # 使用净化后的 CLEAN_ID 执行删除操作
              wrangler pages deployment delete "$CLEAN_ID" --project-name "$PROJECT_NAME" --force
              echo "Successfully initiated deletion for $CLEAN_ID."
            fi
          done

          echo "✅ Old deployments cleanup completed successfully."
