name: Auto Cleanup Old Deployments
on:
  workflow_run:
    workflows: ["Upstream Sync"]  # 同步工作流名称（必须与仓库中一致）
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 jq 和稳定版 wrangler
        run: |
          sudo apt-get install -y jq
          npm install -g wrangler@3.57.0  # 固定版本，避免语法变动

      - name: 自动删除旧部署（仅保留最新2个）
        env:
          # 必须使用 "CLOUDFLARE_API_TOKEN"，而非 "CF_API_TOKEN"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ↓↓↓ 替换为你的 Cloudflare 项目名 ↓↓↓
        run: |
          # 关键修复：项目名 $PROJECT_NAME 必须放在 "list" 前面
          DEPLOY_JSON=$(wrangler pages deployments list $PROJECT_NAME --account-id=$CLOUDFLARE_ACCOUNT_ID --json)
          echo "获取到的部署列表：$DEPLOY_JSON"  # 调试用，可查看原始 JSON 数据
          
          # 提取部署 ID（按时间倒序，跳过前2个，删除剩余）
          DEPLOY_IDS=$(echo "$DEPLOY_JSON" | jq -r '.[].id' | tail -n +3)
          
          if [ -n "$DEPLOY_IDS" ]; then
            echo "开始删除旧部署：$DEPLOY_IDS"
            for ID in $DEPLOY_IDS; do
              # 删除命令：项目名在前，--deployment-id 在后
              wrangler pages deployments delete $PROJECT_NAME --account-id=$CLOUDFLARE_ACCOUNT_ID --deployment-id=$ID --yes
            done
            echo "旧部署清理完成！"
          else
            echo "无需清理，仅保留了最新2个部署"
          fi
