name: Auto Cleanup Old Deployments (Carriage Return Fix)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest wrangler and cleanup old deployments
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          set -e

          echo "Installing the latest version of wrangler..."
          npm install -g wrangler
          
          echo "Installation complete. Verifying version..."
          wrangler --version

          echo "Fetching deployment list for project: $PROJECT_NAME"
          
          # 关键修复：在 awk 处理前，使用 tr -d '\r' 清除所有破坏性的回车符。
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | tr -d '\r' | awk 'NR>2 {print $1}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found or failed to fetch list. Exiting."
            exit 0
          fi

          echo "All deployment IDs found:"
          # 打印ID进行验证，这次应该能看到正常的ID列表
          echo "$DEPLOY_IDS"

          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted:"
          echo "$OLD_IDS"

          for ID in $OLD_IDS; do
            # 由于ID已经被清理干净，这里的命令将可以被正确解析
            echo "Deleting deployment $ID..."
            wrangler pages deployment delete "$ID" --project-name "$PROJECT_NAME" --force
          done

          echo "✅ Old deployments cleanup completed successfully."
