name: Auto Cleanup Old Deployments (Final Version)

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 请确保这里的名称与您的上游同步工作流完全一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest wrangler and cleanup old deployments
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换为您的真实 Cloudflare Pages 项目名
        run: |
          # 脚本开始时，增加 set -e，确保任何命令失败时立即退出
          set -e

          echo "Wrangler not found. Installing the latest version..."
          # 步骤 1: 安装最新版本的 wrangler。这是解决 `command not found` 的关键。
          npm install -g wrangler
          
          echo "Installation complete. Verifying version..."
          # 验证 wrangler 版本，这将显示一个 v3+ 的版本号
          wrangler --version

          echo "Fetching deployment list for project: $PROJECT_NAME"
          
          # 步骤 2: 使用 wrangler v3 的正确语法执行清理
          # 使用 awk 解析 wrangler v3 的表格输出，提取第一列的部署 ID
          DEPLOY_IDS=$(wrangler pages deployment list --project-name "$PROJECT_NAME" | awk 'NR>2 {print $1}')

          if [ -z "$DEPLOY_IDS" ]; then
            echo "No deployments found or failed to fetch list. Exiting."
            exit 0
          fi

          echo "All deployment IDs found:"
          echo "$DEPLOY_IDS"

          # 计算部署数量
          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "Deployment count is $COUNT. No cleanup needed."
            exit 0
          fi

          # 提取需要删除的旧部署 ID（跳过最新的2个）
          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "The following old deployments will be deleted:"
          echo "$OLD_IDS"

          # 循环删除旧部署
          for ID in $OLD_IDS; do
            echo "Deleting deployment $ID..."
            # 使用 wrangler v3 的删除语法
            wrangler pages deployment delete "$ID" --project-name "$PROJECT_NAME" --force
          done

          echo "✅ Old deployments cleanup completed successfully."
