name: Auto Cleanup Old Deployments
on:
  workflow_run:
    workflows: ["Upstream Sync"]  # 同步工作流名称（必须正确）
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 安装必要工具
        run: |
          sudo apt-get install -y jq
          npm install -g wrangler@3.57.0

      - name: 强制删除旧部署（仅保留最新2个）
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ← 必须替换为你的项目名！！！
        run: |
          # 1. 获取所有部署 ID（按时间倒序，最新的在前）
          echo "获取部署列表..."
          DEPLOY_IDS=$(wrangler pages deployments list $PROJECT_NAME --account-id=$CLOUDFLARE_ACCOUNT_ID --json | jq -r '.[].id')
          echo "所有部署 ID: $DEPLOY_IDS"

          # 2. 仅保留最新的2个，删除其余（如果部署数量 > 2）
          if [ $(echo "$DEPLOY_IDS" | wc -w) -gt 2 ]; then
            OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')  # 跳过前2个，取后面的旧部署
            echo "删除旧部署: $OLD_IDS"
            for ID in $OLD_IDS; do
              wrangler pages deployments delete $PROJECT_NAME --account-id=$CLOUDFLARE_ACCOUNT_ID --deployment-id=$ID --yes
            done
          else
            echo "部署数量 ≤ 2，无需清理"
          fi
