name: Auto Cleanup Old Deployments

on:
  workflow_run:
    workflows: ["Upstream Sync"]  # ⚠️ 触发工作流名称，必须和你仓库已有的 workflow 名一致
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 安装依赖（jq + 强制兼容版本 wrangler）
        run: |
          sudo apt-get install -y jq
          npm uninstall -g wrangler || true              # ❗强制卸载可能存在的 v3+
          npm install -g wrangler@2.20.0                 # ✅ 安装支持 pages 的版本
          wrangler --version                             # ✅ 输出版本确认（必须是 2.20.0）

      - name: 自动清理旧部署（仅保留最新2个）
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "libretv"  # ⚠️ 请替换成你的真实 Pages 项目名
        run: |
          echo "账户 ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "项目名: $PROJECT_NAME"

          echo "获取部署列表..."
          DEPLOY_JSON=$(wrangler pages deployments list \
            --project-name="$PROJECT_NAME" \
            --account-id="$CLOUDFLARE_ACCOUNT_ID" \
            --json)

          echo "原始部署 JSON:"
          echo "$DEPLOY_JSON"

          DEPLOY_IDS=$(echo "$DEPLOY_JSON" | jq -r '.[].id')
          echo "所有部署 ID:"
          echo "$DEPLOY_IDS"

          COUNT=$(echo "$DEPLOY_IDS" | wc -l)
          if [ "$COUNT" -le 2 ]; then
            echo "部署数量 ($COUNT) 不超过2个，无需清理。"
            exit 0
          fi

          OLD_IDS=$(echo "$DEPLOY_IDS" | awk 'NR>2')
          echo "准备删除以下旧部署:"
          echo "$OLD_IDS"

          for ID in $OLD_IDS; do
            echo "正在删除部署 $ID..."
            wrangler pages deployments delete \
              --project-name="$PROJECT_NAME" \
              --account-id="$CLOUDFLARE_ACCOUNT_ID" \
              --deployment-id="$ID" \
              --yes
          done

          echo "✅ 旧部署清理完成。"
